rango/urls.py
from django.urls import path
from rango import views
from tango_with_django_project import settings
from django.conf.urls.static import static

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/',
        views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    
    path('tNindex', views.tNindex, name='tNindex'),
    path('tNcourse', views.tNcourse, name='tNcourse'),
    path('tNlogin', views.tNlogin, name='tNlogin'),
    path('tNnote', views.tNnote, name='tNnote'),
    path('tNregister', views.tNregister, name='tNregister'),
    path('tNsearch', views.tNsearch, name='tNsearch'),
    path('tNupload/<int:NoteID>/', views.tNupload, name='tNupload'),
    path('tNupload', views.tNupload, name='tNupload'),
    path('tNuser', views.tNuser, name='tNuser'),
    path('tNnote/<int:NoteID>/', views.tNnote, name = 'tNnote'),
    path('tNnotes/<str:CourseID>/', views.tNnotes, name = "tNnotes"),
    path('serve_docx/<int:NoteID>/', views.serve_docx, name='serve_docx'),
    path('logout/', views.user_logout, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
# The above maps any URLs starting with rango/ to be handled by rango.
    #path('thinkNote/', include('thinkNote.urls')),
    #path('thinkNote/', include('thinkNote.urls', namespace='thinkNote')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(
        max_length=Category.NAME_MAXLEN,
        help_text="Please enter the category name."
    )
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(
        max_length=Page.TITLE_MAXLEN,
        help_text="Please enter the title of the page."
    )
    url = forms.URLField(
        max_length=200,
        help_text="Please enter the URL of the page."
    )
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values; we may not want to include them.
        # Here, we are hiding the foreign key.
        # We can either exclude the category field from the form,
        exclude = ('category',)
        # or specify the fields to include (don't include the category field).
        # fields = ('title', 'url', 'views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
    
        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data
    
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')



#
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class StudentForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = ('YearEnrolled', 'CurrentYearStudent')

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('CourseID', 'Topics', 'file')  # Fields to include in the form
       
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)  # Get the user from kwargs
        self.edited = kwargs.pop('edited', None)  # Get the edited note creator from kwargs
        self.CourseID = kwargs.pop('CourseID', None)  # Get the CourseID from kwargs
        super(NoteForm, self).__init__(*args, **kwargs)
        self.fields['CourseID'].empty_label = 'Select a Course'

        # If CourseID is provided, set it as a hidden field
        if self.CourseID:
            
            self.fields['CourseID'].initial = self.CourseID
            self.fields['CourseID'].widget = forms.HiddenInput()
        
    def save(self, commit=True):
        # Save the form but don't commit to the database yet
        instance = super(NoteForm, self).save(commit=False)
        
        # Set the user field to the current user
        if self.user:
            instance.user = self.user
        
        # Set the edited field to the provided creator (if any)
        if self.edited:
            instance.edited = self.edited
        
        if commit:
            instance.save()  # Save the instance to the database
        
        return instance

    

rango/views.py
import os
from django.shortcuts import get_object_or_404, render
from django.http import FileResponse, HttpResponse
from rango.forms import *
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
from docx2pdf import convert
from django.contrib import messages 
from tango_with_django_project import settings

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

# Use the login_required() decorator to ensure only those logged in can
# access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return redirect(reverse('rango:index'))

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    visitor_cookie_handler(request)

    response = render(request, 'rango/index.html', context=context_dict)

    return response

def tNindex(request):

    courses = Courses.objects.all()
    notes = Note.objects.all()

    return render(request, 'rango/tNindex.html', {'courses' : courses, 'notes':notes})

def tNcourse(request):
    courses = Courses.objects.all()
    
    return render(request, 'rango/tNcourse.html', {'courses': courses})

def tNlogin(request):
     # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

       
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return redirect(reverse('rango:tNindex'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your ThinkNote account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
    
        return render(request, 'rango/tNlogin.html')

def serve_docx(request, NoteID):
    # Fetch the note object
    note = get_object_or_404(Note, NoteID=NoteID)
    
    # Construct the file path
    file_path = os.path.join(settings.MEDIA_ROOT, note.file.name)
    
    # Serve the file with the correct headers
    if os.path.exists(file_path):
        response = FileResponse(open(file_path, 'rb'))
        response['Content-Type'] = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
        response['Content-Disposition'] = f'inline; filename="{os.path.basename(file_path)}"'
        return response
    else:
        return HttpResponse("File not found", status=404)

def tNnote(request,NoteID):

    
    note = Note.objects.get(NoteID = NoteID)

    return render(request, 'rango/tNnote.html', {'note': note})

def tNnotes(request,CourseID):

    notes_from_course = Note.objects.filter(CourseID = CourseID)

    return render(request, 'rango/tNnotes.html', {'course_notes':notes_from_course})

def tNregister(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        students_form = StudentForm(request.POST)

        if user_form.is_valid() and students_form.is_valid():
            # Save the User data
            user = user_form.save(commit=False)
            password = user_form.cleaned_data['password']
            
            user.set_password(password)  
            user.save()

            # Save the Students data
            student = students_form.save(commit=False)
            student.user = user  
            student.save()

            registered = True
            return redirect('login')  # Redirect to the login page after successful registration
       
        else:
            print(user_form.errors, students_form.errors)  # Print form errors for debugging
    else:
        user_form = UserForm()
        students_form = StudentForm()

    return render(request,
                  'rango/tNregister.html',
                  context={'user_form': user_form,
                           'students_form': students_form,
                           'registered': registered})

def tNsearch(request):
    return render(request, 'rango/tNsearch.html')

@login_required
def tNupload(request, NoteID = None):

    if request.method == 'POST':
        # Print the contents of request.POST and request.FILES
        
        if NoteID is not None:
            edit = True
            creator = Note.objects.get(NoteID = NoteID)
            form = NoteForm(request.POST, request.FILES, user=request.user.students, edited=NoteID, CourseID = creator.CourseID,)  # request.user.students is the Students instance

        else:
            edit = False
            creator = None
            form = NoteForm(request.POST, request.FILES, user=request.user.students, edited=NoteID)  # request.user.students is the Students instance

        
        if form.is_valid():
            
            form.save()  # Save the form with the user field set
            messages.success(request, 'File uploaded successfully!')  # Add a success message

            return redirect('rango:tNupload')  # Redirect to the index page after successful upload
        else:

            # Render an empty form for GET requests
            form = NoteForm(user=request.user.students)
            messages.error(request, 'File not uploaded successfully')  # Add a success message
        print("POST data:", request.POST)
        print("FILES data:", request.FILES)
    else:
        if NoteID is not None:
            edit = True
            creator = get_object_or_404(Note, NoteID=NoteID)
            form = NoteForm(user=request.user.students, edited=creator.user, CourseID=creator.CourseID)
        else:
            edit = False
            creator = None
            form = NoteForm(user=request.user.students)

    
    return render(request, 'rango/tNupload.html', {'form': form, 'edit':edit, 'creator' : creator})

def tNuser(request):
    
    notes = Note.objects.filter(user = request.user.id)

    return render(request, 'rango/tNuser.html', {'notes':notes,})

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:tNindex'))




def about(request):
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    return render(request, 'rango/about.html', context=context_dict)

def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}

    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # The .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)

        # Retrieve all of the associated pages.
        # The filter() will return a list of page objects or an empty list.
        pages = Page.objects.filter(category=category)

        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages

        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category

    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None

    # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            cat = form.save(commit=True)
            # Now that the category is saved, we could confirm this.
            # For now, just redirect the user back to the index view.
            return redirect('/rango/')
        else:
            # The supplied form contained errors -
            # just print them to the terminal.
            print(form.errors)

    # Will handle the bad form, new form, or no form supplied cases.
    # Render the form with error messages (if any).
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    # You cannot add a page to a Category that does not exist...
    if category is None:
        return redirect('/rango/')

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        <p>Visits: {{ visits }}</p>
        here is the about page.<br />
        <strong>This tutorial has been put together by Frank</strong><br />
    </div>
    <div>
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat." />
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
    <h1>Add a Page to {{ category.name }}</h1>
    <div>
        <form id="add_page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Add Page" />
        </form>
    </div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
<head>
    <title>
        Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
</head>
<body>
    <style type="text/css" media="screen">
        
    </style>
    <div>
        {% block body_block %}
        {% endblock %}
    </div>
    <div>
        {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
        </div>
    <hr />
    <div>
        <ul>
            {% if user.is_authenticated %}
                <!-- Show these links when the user is logged in -->
                <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'rango:logout' %}">Logout</a></li>
            {% else %}
                <!-- Show these links when the user is NOT logged in -->
                <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                <li><a href="{% url 'rango:login' %}">Login</a></li>
            {% endif %}
            <!-- Outside the conditional statements, ALWAYS show -->
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
    </div>
</body>
</html>

templates/rango/categories.html
<ul>
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
                <li>
                    <strong>
                        <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                    </strong>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
        {% endif %}
    {% else %}
        The specified category does not exist.
    {% endif %}
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for Rango</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}

            <!-- Display each form -->
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        Since you're logged in, you can see this text!<br />
    </div>
    
{% endblock %}

templates/rango/tNbase.html
{% load staticfiles %}
{% load rango_template_tags %}

<!DOCTYPE html>

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title> 
            ThinkNote -
            {% block title_block %}
            {% endblock %}
        </title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}"/>
    </head>

    <body>
        
        <div id="toolBar"><!-- The ThinkNote Sign, search bar, login/sign up or user profile function -->
            
            <a id="tNicon" href="{% url 'rango:tNindex' %}"><strong>Think</strong><em>Note</em></a>
            <hr>
            Search Bar
            <hr>
            {% if user.is_authenticated %}
                <a class="useLoginfo" href="{% url 'rango:user_profile' %}">My profile</a>
            {% else %}
                <p class="useLoginfo"><a href="{% url 'rango:login' %}">Login</a> / <a href="{% url 'rango:index' %}">Sign up</a></p>
            {% endif%}
            <!--


            
            -->
        </div>
        <br>
        <div>

            {%block header_block%}
            {% endblock %}

        </div>
        <br>
        <div>
           
            {% block body_block %}
            {% endblock %}
        
        </div>
        <br>  
    </body>

</html>

templates/rango/tNcourse.html
{% extends 'rango/tNbase.html' %}
<!DOCTYPE html>

{% block title_block %}
    Course Name
{% endblock %}

{% block header_block %}
    <h1>Courses</h1>
{% endblock %}

{% block body_block %}
      
    <div>
        <h2>List of notes</h2>
        {% if categories %}
            <ul>
                {% for category in categories %}<!--here shows the notes-->
                    <li><a href = "/rango/category/{{category.slug}}">{{category.name}}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no notes present.</strong>
        {% endif %}
    </div>
    <br>
    <div>
        {% if user.is_authenticated %}
            <a href = "{% url 'thinkNote:upload' %}">botton-Upload a note</a>
        {% else %}
            Login to upload notes.
        {% endif%}
    </div>
{% endblock %}

templates/rango/tNindex.html
{% extends 'rango/tNbase.html' %}
<!DOCTYPE html>

{% block title_block %}
    Homepage
{% endblock %}

{% block header_block %}
    <h1 id="tNicon">Unlock Knowledge Through <strong>Think</strong><em>Note</em></h1>    
{% endblock %}

{% block body_block %}
    <h2 id="slogan">Connecting Minds, Sharing Notes.</h2>
    <br>
    
    <div class="mainContent">
        <h2>Recommended notes:</h2>
        {% if categories %}
            <ul>
                {% for category in categories %}<!--here shows the notes-->
                    <li>list</li>
                {% endfor %}
            </ul>
        {% else %}
            There are no notes present.
        {% endif %}
    
        <h4>Text File Content for test</h4>
        {% if file_content%}
            <pre>{{ file_content }}</pre>
        {% endif %}
        
 
    </div>
    <br>
    <div class="sideBar">
        <h2>List of courses</h2>
        {% if pages %}
            <ul>
                {% for page in pages %}<!--here shows the courses-->
                    <li>list</li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no notes present.</strong>
        {% endif %}

    </div>

    <div>

    </div>
{% endblock %}

templates/rango/tNlogin.html
{% extends 'rango/tNbase.html' %}
<!DOCTYPE html>

{% block title_block %}
    User Login
{% endblock %}

{% block header_block %}
    <h1>User Login</h1>    
{% endblock %}

{% block body_block %}
    
    <div><!--Login function-->
        <h1>Login to ThinkNote</h1>
        <form id="login_form" method="post" action="{% url 'rango:tNlogin' %}">
        {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />
            <input type="submit" value="submit" />
        </form>
    </div>

{% endblock %}

templates/rango/tNregister.html
{% extends 'rango/tNbase.html' %}
<!DOCTYPE html>

{% block title_block %}
    Register
{% endblock %}

{% block header_block %}
    <h1>User Register</h1>    
{% endblock %}

{% block body_block %}
    
    <div><!--Register function-->
        <h1>Register for ThinkNote</h1>
        {% if registered %}
            <strong>thank you for registering!</strong>
            <br>
            <a href="/rango/">Return to the homepage.</a>
        {% else %}
            <strong>register here!</strong>
            <form id = "user_form" method="post" action="{% url 'rango:tNregister' %}" enctype="multipart/form-data">

                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}

                <input type="submit" name="submit" value="Register" />
            </form>
        {% endif %}
    </div>

{% endblock %}

templates/rango/tNsearch.html
{% extends 'rango/tNbase.html' %}
<!DOCTYPE html>

{% block title_block %}
    {% if searchTitle %}
        {{ searchTitle }}
    {% else %}
        Search
    {% endif %}
{% endblock %}

{% block header_block %}
    {% if searchTitle %}
        <h1>{{ searchTitle }}</h1>
    {% else %}
        <h1>Search Title not found</h1>
    {% endif %}
{% endblock %}

{% block body_block %}
      
    <div>

        {% if searchResults%}
            <h3>Maybe you want to find: </h3>
            <br>
            <ul>
                {% for searchResult in searchResults %}
                    <li></li><!--here links to different notes-->
                {% endfor %}
            </ul>
        {% else %}
            <strong>No results found.</strong>
        {% endif %}       
    </div>
    
{% endblock %}

templates/rango/tNuser.html
{% extends 'rango/tNbase.html' %}
<!DOCTYPE html>

{% block title_block %}
    My Profile
{% endblock %}

{% block header_block %}
    <h1>My Profile</h1>
{% endblock %}

{% block body_block %}
      
    <div>
        <h2>My notes</h2>
        {% if categories %}
            <ul>
                {% for category in categories %}<!--Here shows the notes-->
                    <li><a href = "/rango/category/{{category.slug}}">{{category.name}}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            You have not upload any notes yet.
        {% endif %}
    </div>
    <br>
    <div>
        {% if categories %}
            <p>Edit notes</p>
            <a href = "{% url 'rango:tNupload' %}">botton-Upload a note</a>
            <p>Delete note</p>
        {% else %}
        {% endif%}
    </div>
{% endblock %}